#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false
#  registry:
#    address: nacos://192.168.3.24:8848?namespace=lmy-live-test&&username=lmy&&password=lmy
#server:
#  servlet:
#    context-path: /live/api
#  port: 8071
#spring:
#  application:
#    name: lmy-live-bank-api
#  data:
#    redis:
#      port: 6379
#      host: 192.168.3.24
#      password: redis
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 100
#          max-idle: 10
#lmy:
#  rmq:
#    consumer:
#      nameSrv: 192.168.3.24:9876
#      groupName: ${spring.application.name}
#    producer:
#      nameSrv: 192.168.3.24:9876
#      groupName: ${spring.application.name}
#      retryTimes: 3
#      sendTimeout: 3000